### ISSUE TITLE
Broken EAP cluster after machine restart

### ISSUE THREAD

**Issue by mnovak1** [Azure/rhel-jboss-templates#17]
There is broken cluster (in standalone, multivm and vmss template) after restart of machines. Issues seems to be that bind address which is used by clustering and set in JAVA_OPTS in `... -Dboss.bind.address.private=....` is empty after VM is restarted. 

The only workaround is to restart the `eap7-standalone.service` service by: 
```systemctl restart eap7-standalone.service```

**Comment by mnovak1** [comment]
Looks like it can be fixed by edit `/etc/systemd/system/multi-user.target.wants/eap7-standalone.service` and modify those 2 lines:
```
After=syslog.target network.target NetworkManager-wait-online.service
Wants=NetworkManager-wait-online.service
```

**Comment by mnovak1** [comment]
Tracking jira issue: https://issues.redhat.com/browse/WFWIP-388

**Comment by AdarshRazor** [comment]
hey @mnovak1, I made changes in eap7-standalone.service as you suggested. There was also some bug in the script where the hostname was not getting captured while assigning to bind.address.private. After that, I added the cron job to restart the systemctl service every time RHEL VM restarts. Here are the following PR links which I raise. Please go through it once. I wanted to know which log file are you looking up for getting the broken cluster details or where exactly are you finding this issue. According to EAP [documentation](https://access.redhat.com/solutions/18664), there should be a **boot.log** file that contains the session binding address details but there is no boot.log file in the RHEL VM which is getting deployed by the template.

• [Standalone – BYOS](https://github.com/Azure/rhel-jboss-templates/pull/18)
• [Standalone – PAYG](https://github.com/Azure/rhel-jboss-templates/pull/19)
• [MultiVM – BYOS](https://github.com/Azure/rhel-jboss-templates/pull/20)
• [MultiVM – PAYG](https://github.com/Azure/rhel-jboss-templates/pull/21)
• [VMSS – BYOS](https://github.com/Azure/rhel-jboss-templates/pull/22)
• [VMSS - PAYG](https://github.com/Azure/rhel-jboss-templates/pull/23)

**Comment by mnovak1** [comment]
Hi Adarsh,

thanks for the fixes. I've checked VMSS - PAYG
<https://github.com/Azure/rhel-jboss-templates/pull/23> and provided a
review. There is a topic for discussion. Could you take a look, please?

Whether the IP address was assigned to jboss.bind.address,private after VM
restart I was checking by using following command:
$ ps aux | grep java
...  -Djboss.bind.address.private=10.1.0.5 -D....

It must not be empty (at least not in multivm and vmss template, standalone
does not form a cluster).

Otherwise the information that cluster is formed is visible from server.log
(/opt/rh/eap7/root/usr/share/wildfly/standalone/log/server.log). There
should be log message like -
2021-09-29 10:22:40,209 INFO  [org.infinispan.CLUSTER] (MSC service thread
1-3) ISPN000094: Received new cluster view for channel ejb:
[jbosseap-serverserver000001|1] (2) [jbosseap-serverserver000001,
jbosseap-serverserver000000]

Important thing is the list of cluster nodes in
....[jbosseap-serverserver000001, jbosseap-serverserver000000]. If there is
just single server and not the other one then there is something wrong.

Thanks,
Mirek

**Comment by mnovak1** [comment]
@AdarshRazor hi, did you manage to take a look at ^, please?

**Comment by AdarshRazor** [comment]
Hey @mnovak1,  I did that cron job to restart the eap7-standalone.service every time VM restarts. If I remove that then the cluster fails to load. That cron job only works when the VM gets restart. I tried removing the corn job and restarted the VM and it was failing to assign the IP.

**Comment by mnovak1** [comment]
Hi @AdarshRazor thanks. I'll give it a try as well. I think restarting the service should be avoided as it causes additional restart of EAP 7 and unavailability/disruption of service. We need to find a way how to start the service after IP address is allocated.

**Comment by AdarshRazor** [comment]
Yaa, I am getting the word @mnovak1 . I will try to find a way around to make this code more efficient. Will keep you posted. Let me know your findings on the script. That will help this case close fast.

**Comment by mnovak1** [comment]
@AdarshRazor I'm trying VMSS PAYG template from `master` and when I restart both of the started server then I see that `private` address is not assigned and cluster is broken (just a single node is in the list).

I tried to modify `/etc/systemd/system/multi-user.target.wants/eap7-standalone.service` and change it to:
After=syslog.target network.target NetworkManager-wait-online.service
Wants=NetworkManager-wait-online.service

on both servers. Then I restart the servers and see that `private` address is assigned and cluster is formed (there are 2 different nodes in the list):
```2021-10-05 12:13:46,136 INFO  [org.infinispan.CLUSTER] (MSC service thread 1-1) ISPN000094: Received new cluster view for channel ejb: [jbosseap-serverservers000000|8] (2) [jbosseap-serverservers000000, jbosseap-serverservers000001]```

I'll try your branch if possible. I remember it required a manual tweak not to take `master` branch template and use your branch when deploying it.

**Comment by mnovak1** [comment]
hi @AdarshRazor , thanks for the update. We'll trigger our TS against those PRs and let you know.

**Comment by AdarshRazor** [comment]
@istraka , I have raised another commit in which I have changes the codes back to as it was for echoing in the conf file. Please review it.

**Comment by AdarshRazor** [comment]
@istraka any update on the tests? Let me know if there is anything.

**Comment by istraka** [comment]
Hi @AdarshRazor 
There is one unresolved issue on https://github.com/Azure/rhel-jboss-templates/pull/19/files#r735645443.

Tests have shown no error. However we have some issues in out preparation phase with BYOS VMSS template tests.

**Comment by AdarshRazor** [comment]
@istraka , Please check, I have raised the PR with the update. Please test and review it.

**Comment by AdarshRazor** [comment]
Hi @istraka, any update ?? Let me know if there is anything.

**Comment by istraka** [comment]
@AdarshRazor tests passes. However I have one concern. There is one change https://github.com/Azure/rhel-jboss-templates/pull/19/files#diff-db0f416670fab055559bb152e8e7d8040e9079cbaabf2499148ba0b124138a7aL87 that is basically everywhere except https://github.com/Azure/rhel-jboss-templates/pull/18/files. Can you provide more info why is that?

**Comment by AdarshRazor** [comment]
@istraka , I have removed the double quote from the echo command. Hope it will resolve the issue. If you asking about the deletion of "storageAccountResourceGroup". There is no use of that parameter in the mainTempalte.json file.

**Comment by jamesfalkner** [comment]
I believe this issue has been fixed. @istraka can you confirm?

**Comment by mnovak1** [comment]
I tried multivm and vmss template (eap73) and issue is gone in those templates.

**Comment by mnovak1** [comment]
I see the same fix is applied to eap74 templates. Closing the issue.
