### ISSUE TITLE
Set unique node-identifier attribute on the /subsystem=transactions

### ISSUE THREAD

**Issue by mnovak1** [Azure/rhel-jboss-templates#24]
EAP 7 is using `node-identifier` as unique ID to be able to distinguish which transaction on remote resource (like database or messaging broker) was started by it. For this reason if there are multiple EAP 7 accesing the same resource they must have different `node-identifier`. 

This ID could be taken for example from hostname of the node, important is that it remains the same after restart of the VM:
```
./jboss-cli.sh --connect --command="/subsystem=transactions:write-attribute(name=node-identifier,value=<node-id>)"
```

[1] https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/managing_transactions_on_jboss_eap/index#transactions_unique_node_identifier

**Comment by jamesfalkner** [comment]
Turns out the `node-identifier` must be 23 character or less. This presents a problem when hostnames are long and using `$(hostname)` for the identifier. Looking for alternatives, any suggestions? I'm thinking some kind of hash function.

**Comment by jamesfalkner** [comment]
I'm going with

```sh
NODE_ID=$(uuidgen | sed 's/-//g' | cut -c 1-23)
```

It's not cryptographically secure, but unique enough for this use case.

**Comment by mnovak1** [comment]
This issue is fixed. Closing the issue.
