### ISSUE TITLE
TTK reports failures that are silently ignored by GitHub workflow

### ISSUE THREAD

**Issue by jamesfalkner** [Azure/rhel-jboss-templates#55]
See for example https://github.com/Azure/rhel-jboss-templates/runs/5342285639?check_suite_focus=true

There is a failure reported in the output as can be seen, yet the workflow succeeds. The errors should be caught and cause the workflow to fail.

![image](https://user-images.githubusercontent.com/861894/156197869-3d739aa9-6eef-40e3-b5c3-0fb9ec415f65.png)

**Comment by edburns** [comment]
WIP https://github.com/edburns/rhel-jboss-templates/actions/runs/1918832763
