### ISSUE TITLE
Azure templates deployment fail

### ISSUE THREAD

**Issue by laDok8** [Azure/rhel-jboss-templates#57]
Azure CLI fails to download war files (404 error) using [mainTemplate.json](https://github.com/Azure/rhel-jboss-templates/blob/master/eap74-rhel8-payg-vmss/src/main/arm/mainTemplate.json) file.
Pressumably because or recent refractoring paths do not match [templates](https://github.com/Azure/rhel-jboss-templates/blob/master/eap74-rhel8-payg-vmss/src/main/arm/mainTemplate.json#L240) and [script](https://github.com/Azure/rhel-jboss-templates/blob/master/eap74-rhel8-payg-vmss/src/main/scripts/jbosseap-setup-redhat.sh#L42) fails.

**Comment by mnovak1** [comment]
I took a look at it and it looks like that `eap-session-replication.war` file cannot be downloaded. Looking at the template the issue is on line: 
https://github.com/Azure/rhel-jboss-templates/blob/2cb869c8b8b0c6821ac4b5da6ec6f3fd2d725f5d/eap74-rhel8-payg-multivm/src/main/arm/mainTemplate.json#L240

Code:
`"scriptFolder": "scripts",` is wrong directory. Newly `eap-session-replication.war` is located in `bin` directory. To fix this issue all templates must change `"scriptFolder": "bin"`

@jamesfalkner FYI

**Comment by jamesfalkner** [comment]
The .war file is in a directory called `bin/` in the _source code_ repository, but in the Marketplace offering zip files that I upload to Marketplace, the .war file is in the `scripts/` directory inside the zip file. 

How did you create the artifact storage content?

**Comment by jamesfalkner** [comment]
If I update the path in the `mainTemplate.json` it will break the offers currently on Marketplace, so a different solution is needed.

**Comment by mnovak1** [comment]
`... but in the Marketplace offering zip files that I upload to Marketplace, the .war file is in the scripts/ directory inside the zip file.`

so there is different dir structure on Marketplace? I thought it's the same.

**Comment by jamesfalkner** [comment]
Yeah, it's now different now that the .war file moved into the `bin/` directory in the source code repo. In the binary distros it's in the `scripts/` directory so as to not break the script(s) that run at deploy time. So you would need to create a storage account and place the files in the right place (script and .war file in the `scripts/` directory) in the storage account for the script(s) to consume the content (and point to it with `_artifactsLocation`).

**Comment by jamesfalkner** [comment]
There is powershell code in [here](https://github.com/Azure/rhel-jboss-templates/blob/master/Deploy-AzTemplate.ps1) that creates a storage account and dumps the files into the right place, but this could also be done with `az` pretty easily. If you had some example bash shell script that creates the files, would that help?

**Comment by laDok8** [comment]
Would it be possible to change _artifactsLocation argument from specifying parent directory of war file to it's directory. Currently we are relying on directory structure hard coded in json and afaik it's always in form `fileUrl='$artifactsLocation"scripts"...'`

**Comment by jamesfalkner** [comment]
Looks good to me. @mnovak1 and @laDok8 please have a look. With the binary offer .zip files now having the .war file in the `bin` directory, it's a simple matter to change the script to use it.

**Comment by laDok8** [comment]
LGTM, thanks
